#!/bin/sh
echo "Enter a character"
read a
case "$a" in
a | e | i | o | u )
echo "$a is a Vowel";;
0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 )
echo "$a is a Number";;
*) echo "$a is a consnant";;
esac 
exit 0

#!/bin/sh
echo "Enter the year"
read a
if [ `expr $a % 4` -eq 0 ] ; then
echo "it is a leap year"
else
echo "it is not a leap year"
fi
exit 0

#!/bin/sh
echo "Is it morning? Please answer yes or no"
read timeofday
case "$timeofday" in
yes) echo "Good Morning";;
no ) echo "Good Afternoon";;
y ) echo "Good Morning";;
n ) echo "Good Afternoon";;
* ) echo "Sorry, answer not recognized";;
esac
exit 0

#!/bin/sh
fun() {
echo "Function fun is executing"
}
echo "script starting"
fun
echo "script ended"
exit 0


#!/bin/sh
sample_text="global variable"
fun() {
local sample_text="local variable"
echo "Function fun is executing"
echo $sample_text
}
echo "script starting"
echo $sample_text
fun
echo "script ended"
echo $sample_text
exit 0

#!/bin/sh
yes_or_no() {
echo "Is your name $* ?"
while true
do
echo -n "Enter yes or no: "
read x
case "$x" in
y | yes ) return 0;;
n | no ) return 1;;
* ) echo "Answer yes or no"
esac
done
}
echo "Original parameters are $*"
if yes_or_no "$1"
then
echo "Hi $1, nice name"
else
echo "Never mind"
fi
exit 0
